### ISSUE TITLE
Screen output enabling and disabling.

### ISSUE THREAD

**Issue by jimyehoo** [bitfocus/companion-module-renewedvision-propresenter#81] opened 2021-06-26 16:16 UTC
looking for Ctrl-1 or Cmd-1 function so I can switch between slides and VLC video playbacks.  I don't know if this is possible, a Screen enable and Screen disable command instead of a toggle.  Really don't like this toggle action on the app because when I combines a few other commands together (such as screen disbale and VLC full screen), each apps has to be in the right state or it create more chaos than what it tries to solve, but this is the app issue and not Companion or this plugin issue...  Anyway, right now I am doing that via Vicreo OSX command targeting ProPresenter, but if this is in the plugin, then it's even more reliable and works on Windows side.
And what Custom Action is for? can't find any info here.

**Comment by greyshirtguy** [comment] 2021-06-30 02:21
There is no support for turning display on/off in the remote protocol (which is how we talk to ProPresenter) .
This leaves you no option but to find a "workaround".
Using Vicreo to send Ctrl/Cmd-1 is one such work-around (but, it is a toggle - as you say).

I have asked RV in the past if they would consider updating the protocol to add more features/control to it.
They weren't against the idea - they were just too busy with other features/improvements.

They have indicated to me recently that they may have more time soon to devite to this! So I will definitely ask about controlling the output again!

Failing that, I have some ideas for workarounds - that would take a lot of effort to make and probably would not be 100% reliable - so I have not yet rushed into making them.  If we don't get any updates to the protocol in the next few months to control output - I will try to create a workaround!

**Comment by greyshirtguy** [comment] 2021-06-30 02:27
Oh, and the custom action.....
That's not for general use by end users. It's there in case I need a quick way to support users with a new/updated command without them needing to wait for an updated module.

eg. Imagine there is some breaking change to the protocol that requires a new/updated message to be sent to perform an existing action (Next slide for example).....In the past, everyone has to wait days/weeks for the module to be updated.....

Now I can say to people who are desparate: just use this custom action "{updated command for next slide etc}" and it will work and trigger next slide while you wait for updated module.

**Comment by greyshirtguy** [comment] 2021-06-30 02:32
For example:  The protocol has a new update found in the latest Mac beta.... You can now control the active Look!
RV is not finished yet though - It still needs feedback and needs to be added to Windows version...

But if you really wanted to, you could right now, create a custom action with the command:
`{"action":"looksTrigger","lookName":"Your Look Name"}`
And that button will trigger that look!!! (only in latest Mac beta so far).

Once this feature is in production release on both platforms, I will update module with new actions to support controlling looks!!!

**Comment by greyshirtguy** [comment] 2022-01-24 02:23
Still no API support to toggle output on/off.
Closing this issue as it is a duplicate of [53](https://github.com/bitfocus/companion-module-renewedvision-propresenter/issues/52) which I will leave open to track any future changes in API that enable this feature one day.

**Closed by greyshirtguy** 2022-01-24 02:23 UTC
