### ISSUE TITLE
Save Button Grayed Out

### ISSUE THREAD

**Issue by glazeddonutsproject** [bitfocus/companion-module-renewedvision-propresenter#72] opened 2021-04-13 00:11 UTC
Hello All,

When I try to add Propresenter, the save button is grayed out and I cannot save the new settings while adding or editing on Mac OSX Catalina in Chrome. I verified I have all of the settings correct.

**Comment by greyshirtguy** [comment] 2021-04-13 00:36
Ohh I see what you mean....This seems to be only with the new WebUI.
It seems you need to fill out all fields (that have validity checks - like the follower-IP).
As a workaround, just fill out "Follower-ProPresenter IP" with say 127.0.0.1 (you can leave the "Auto-Control Follower ProPresenter?" set to NO)

Hey @josephdadams - do you know is this intended behaviour of the new WebUI - Save is disabled until all config fields with Regex: checks have valid values? (Am I missing some obvious way to make some fields optional?)

**Comment by josephdadams** [comment] 2021-04-13 00:40
@Julusian do we still have support for a "required" boolean on config fields?

@greyshirtguy probably good to just put in `127.0.0.1` as a default and set the default value for auto-control follower to no. Can you add that?

**Comment by glazeddonutsproject** [comment] 2021-04-13 00:41
Thanks for the quick response! I'll try that.

**Comment by Julusian** [comment] 2021-04-13 09:39
@josephdadams yeah, required is still supported for input types that I could figure out how it should behave (number and textinput).
For textinput the regex is also expected to pass, maybe that is wrong though?

**Comment by greyshirtguy** [comment] 2021-04-13 10:32
ProPresenter module has a config field for an _optional_ IP address to connect to.
Of course, that _optional_ config field has regex: self.REGEX_IP.
However, the current logic of the edit module page seems to _disable_ the Save button until that field has a value this is validatied by regex: self.REGEX_IP
But this field is optional! Ideally the user should _not_ have to fill it out if they are not using that feature!
I could, as @josephdadams said earlier, default it to some valid dummy ip (127.0.0.1 eg) but that is probably asking for trouble as that IP might be a _bad_ default depending on the specific setup/requirements of each user.

**Comment by Julusian** [comment] 2021-04-13 11:37
Do you remember how the old ui acted? Did it highlight that box as red? (meaning it failed the regex)

I've just had a quick look at various other modules, and a majority of the 5 I sampled at random don't set `required: true` when also setting a regex. Even my own modules dont set required.

But this is a change that will cause issues like this in various modules, so it would be safest to make it behave like before for now and rethink it later. I shall do this when I have some time

**Comment by Julusian** [comment] 2021-04-20 21:01
This is fixed now.
The regex is only run when the field is either marked as required, or if it has a value set.

**Closed by Julusian** 2021-04-20 21:01 UTC
