### ISSUE TITLE
Timeline play/pause/reset for current presentation without specifying path

### ISSUE THREAD

**Issue by timhodson** [bitfocus/companion-module-renewedvision-propresenter#33] opened 2020-04-18 11:57 UTC
My use case is that I don't want to have to reprogram keys every week for a different set of songs. our church service playlists often have different formats with different numbers of items.

What I want to be able to do is move to the next presentation in a playlist, and trigger play on the timeline for that presentation.

Currently I am using the iOS app to control slides, because it allows me this freedom to easily move from presentation to presentation... but... it's another device on a table, and I'd rather be able to do all things via companion.

Is this possible?

**Comment by greyshirtguy** [comment] 2020-04-23 12:26
Hi Tim

Sorry about delay! I've been super busy with my day job in IT working from home mean more remote admin work -> which is a slower -> which mean busy times!

I did some poking around, and noticed that leaving presentationpath blank seems to default to the current document in pro6 and pro7 when sending the "TimeLine Play/Pause" action - so at least that action works on the "current presentation" without needed to put in the presentationpath.

The only tricky part here is that there is nothing in the remote protocol (which is what we use in Companion to control ProPresenter) to "select next presentation".  - The only way the remote protocol allows to select a presentation is to use the "Specific Slide" action to trigger one of it's slides and you have to identify which presentation by its presentationPath.

We could consider doing something crude and trying to keep track of the position of the current presentation in the playlist - but it can be risky if the local state gets out of sync!  I might have a think - maybe I'm missing something obvious! I dont think I am, but I'll think about it!

**Comment by timhodson** [comment] 2020-04-24 20:37
Thanks for looking into this, appreciated. 

>I did some poking around, and noticed that leaving presentationpath blank seems to default to the current document in pro6 and pro7 when sending the "TimeLine Play/Pause" action - so at least that action works on the "current presentation" without needed to put in the presentationpath.

Did you mean poking around with the propresenter remote control protocol? or with the current companion interface for PP?  I have a Timeline play pause action on a companion button at the moment which doesn't have a path, and with a slide selected in a peresentation, there is no trigger of the timeline.

I noticed earlier today that I can get around the next presentation selection not being in the remote protocol issue, by sending an up or down arrow keypress action to a key listener on the machine running propresenter.  I can then use a right arrow keypress to trigger the first slide in that presentation, and then the only missing piece is triggering the timeline to play.

Again, thanks for looking!

**Comment by RylandRussell** [comment] 2021-03-25 16:10
I am interesting in this kinda as well.  I am trying to use companion to "clear" everything BESIDES my announcement feed in the lobbies.  Companion can do this by recalling a specific slide that has all the other clear actions assigned to it.

The problem is that timelines continue to play unless clear all or stop button is pressed.  I thought I could add the timeline start/stop command to the streamdeck button, leaving presentation path blank, but it doesn't seem to stop the current presentations timeline.  

Any ideas?

**Comment by RylandRussell** [comment] 2021-03-25 16:18
So instead of pointing to a specific slide that had all the clear commands on them, I instead made a button using all the companion "clear" commands besides clear all and it worked! The timeline stops!

**Comment by greyshirtguy** [comment] 2021-03-26 05:25
Hello.

I Took a deeper look at this today....

On Windows 10, Both Pro6 and Pro7 allow sending Timeline play/pause without specifying the presentation path - and **it works**.
On MacOS, **neither Pro6 or Pro7 will work** without  specifying the presentation path.

As far as I can tell, this seems to be the intrinsic behviour.  (It might even be a fluke that ProPresenter on Windows handles not having the presentation path since the RV mobile Remote App always sends the presentation path - and it's the remote protocol that this module uses).

However, all is not lost!  If you want, I have a work-around for you that is a bit more of a setup, but it does give you ability to start/stop timeline of active presentation (without needing to know it's path)

**Use MIDI** !
MIDI note 14 will **start** timeline of the active document and MIDI note 15 will **stop** the timeline of the active document.

Steps:
1. Add the Midi-Relay Module to Companion
2. Install MIDI-Relay client listener app on your ProPresenter computer.
3. Add a button to send MIDI note 14 for start and 15 for stop.

Tip: MIDI can also do some other things that the remote protocol cannot (eg toggle Props on/off)

eg:
![image](https://user-images.githubusercontent.com/1886513/112586259-95b28f80-8e4f-11eb-8a25-5fc1e346e62d.png)

**Comment by greyshirtguy** [comment] 2021-04-14 03:42
Still no way for remote protocol to do this. MIDI still best option

**Comment by chanx** [comment] 2022-11-07 07:21
seems like this module is using WS protocol? how about the new openapi from propresenter (https://openapi.propresenter.com/)? On the documentation we have https://openapi.propresenter.com/#/Playlist/playlistFocusedNextTrigger to do the next cue on playlist. Is there something we can do to apply that function?

**Comment by greyshirtguy** [comment] 2022-11-07 07:39
The module does use the remote protocol (via a Web Socket connection).
I plan on making a NEW module soon that uses the new API only (without any reverse-engineered  web-socket connection).

In the meantime, you can easily use the new API right now - just add the Generic HTTP module and call any Pro7 API you like. 

Including `/v1/presentation/active/timeline/pause` to pause the timeline of the _active presentation_ without specifing the presentation path.

Note that docs also include  `/rewind` and `/play` for the timeline of the activepresentation.

Here is an example of using HTTP module to pause timeline (when Comanion is running on same computer as Pro7 that is listening on port 50001)

![image](https://user-images.githubusercontent.com/1886513/200252377-d9164067-bea1-4ab5-8d67-b6ba8f7924cf.png)

**Closed by greyshirtguy** 2022-11-07 07:39 UTC
